name: Coverage

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: go mod download && go mod verify


    - name: Delete coverage
      run: rm -rf ./coverage

    - name: Run Coverage
      run: |
            mkdir -p ./coverage
            go test -coverprofile=./coverage/coverage.out ./...
            go tool cover -html=./coverage/coverage.out -o ./coverage/coverage.html

    - name: Add build to repo
      run: |

            git config --global user.name "Github Actions"
            git config --global user.email "${{secrets.MAIL}}"

            git add -A
            git commit -m "Add coverage"
            git push
