name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io # Or docker.io for Docker Hub
        token: ${{ secrets.DOCKERACCESSTOKEN }}

    - name: Build and Push Docker Image
      id: docker_build
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ghcr.io/programmierigel/pwmanager:latest
          



