name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Login to Docker
      run: echo ${{secrets.DOCKERACCESSTOKEN}} | docker login ghcr.io -u programmierigel
    - name: Build
      run: make build-docker
    - name: Rename
      run: docker image tag programmierigel/pwmanager ghcr.io/programmierigel/pwmanager:latest
    - name: Push
      run: docker push ghcr.io/programmierigel/pwmanager:latest
