name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_run:
      workflows: ["Coverage"]
      types:
        - completed
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: go mod download && go mod verify

    - name: Delete build
      run: rm -rf ./build/pwmanager.exe
    - name: Run check
      run: make build

    - name: Add build to repo
      run: |
            git config --global user.name "Github Actions"
            git config --global user.email "${{secrets.MAIL}}"

            git add -A
            git commit -m "Add build"
            git push
