name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: go mod download && go mod verify


    - name: Delete build
      run: rm -rf ./build/pwmanager.exe
    - name: Run check
      run: make build

    - name: Run Coverage
      run: |
            mkdir -p ./coverage
            go test -coverprofile=./coverage/coverage.out ./...
            go tool cover -html=./coverage/coverage.out -o ./coverage/coverage.html

    - name: Add build to repo
      run: |
            git config --global user.name "Github Actions"
            git config --global user.email "${{secrets.MAIL}}"

            git add -A
            git commit -m "Add build && coverage"
            git push
